apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappbruh-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappbruh-fe
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myappbruh-fe
    spec:
      containers:
        - name: myappbruh-fe
          image: myappbruh-fe:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
