version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3901:3901"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - default
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - default
networks:
  default:
    driver: bridge