apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappbruh-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappbruh-be
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myappbruh-be
    spec:
      containers:
        - name: myappbruh-be
          image: myappbruh-be:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3901
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
