name: Build and Deploy to Minikube

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          eval $(minikube docker-env)
          docker build -t myappbruh-be:latest ./backend
          docker build -t myappbruh-fe:latest ./frontend

      - name: Source bashrc and Deploy to Minikube
        run: |
          source ~/.bashrc
          kubectl apply -f backend/deployment.yaml
          kubectl apply -f backend/service.yaml
          kubectl apply -f frontend/deployment.yaml
          kubectl apply -f frontend/service.yaml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/myappbruh-be
          kubectl rollout status deployment/myappbruh-fe
